credentials:
  usernames:
    admin_acme:
      email: admin@acmecorp.com
      name: Acme HR Admin
      password: $2b$12$b1ZaxDe5p8w/sgQo3kEeceU0KMr/XnIkvQT7ZDpZwFmgWTVaLn8bS
      organization: org_acme
      role: admin
      failed_login_attempts: 0
      logged_in: false
    john_doe:
      email: john@acmecorp.com
      name: John Doe
      password: $2b$12$BTao9JQ6VIPZz6DHvPG35uwC/729NYpmE0eEek40vprxbWjQ/QGqy
      organization: org_acme
      role: employee
      failed_login_attempts: 0
      logged_in: false
    testuser:
      email: ''
      name: ''
      password: $2b$12$tvFRLQHIZCzr1MvZHWR8Veeyxy30XO7SO52XPoAPiIy204HEQTU0a
      organization: org_acme
      role: employee
cookie:
  expiry_days: 0
  key: dayone_secret_signature_key_2026
  name: dayone_login
preauthorized:
  emails: []
